name: flutter_lokalise_example

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lokalise:
    path: ..

flutter_lokalise:
  project_id: YOUR_LOKALISE_PROJECT_ID
  api_token: YOUR_LOKALISE_API_TOKEN
  include_tags:
    - tagged_key
